### **Generating Dataset**

This notebook was used to generate the query dataset which details all known and generated queries for each function of the BBO capstone challenge.

In [1]:
# Dependencies,
import numpy as np
import pandas as pd

Let us write a function to return a Pandas `DataFrame` whose rows are the evaluations in the BBO challenge. Known evaluations supplied for the challenge possess negative integers in `Query Number` field. On the other hand, those generated by the optimiser are associated with positive integers in the same field.

In [35]:
def create_df(func_num):

    # Reading Excel file for optimiser evalutions,
    df = pd.read_excel(f"Function {func_num}/evals.xlsx", header=1)
    df = df.loc[:, ~df.columns.str.contains("Unnamed")]

    # Loading known evalations (warm-start evals),
    X, y = np.load(f"Function {func_num}/initial_inputs.npy"), np.load(f"Function {func_num}/initial_outputs.npy")

    # Creating rows and concatening with existing df,
    rows = []
    for k, (x, fx) in enumerate(zip(X, y), start=1):
        row = {"Query Number": -k}
        row.update({
            f"x{i+1}": val for i, val in enumerate(x)
        })
        row["f(X)"] = fx
        rows.append(row)

    new_rows = pd.DataFrame(rows)
    df_new = pd.concat([new_rows, df], ignore_index=True)
    
    return df_new

Now we create a data frame for each black-box function and save it as a CSV file,

In [43]:
# Creating dataframe,
j = 8
df = create_df(func_num=j)

# Saving to CSV,
df.to_csv(f"dataset/func_{j}_evals.csv", index=False)
df

,Query Number,x1,x2,x3,x4,x5,x6,x7,x8,f(X)
0,-1,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,-2,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,-3,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,-4,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,-5,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,-6,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,-7,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,-8,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,-9,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,-10,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,-11,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,-12,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,-13,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,-14,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,-15,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,-16,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,-17,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,-18,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,-19,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,-20,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,-21,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,-22,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,-23,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,-24,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,-25,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,-26,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,-27,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,-28,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,-29,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,-30,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,-31,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,-32,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,-33,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,-34,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,-35,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,-36,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,-37,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,-38,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,-39,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,-40,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,1,0.006410,0.000000,0.090590,0.000000,1.000000,0.321248,0.000000,0.359559,9.795089
41,2,0.000000,0.088234,0.340904,0.000000,0.665972,0.456168,0.000000,1.000000,9.713338
42,3,0.140996,0.022376,0.238893,0.000000,0.406098,0.634525,0.000000,0.265171,9.735390
43,4,0.000000,0.211203,0.099416,0.434209,0.758735,0.615735,0.151123,0.613943,9.873630
44,5,0.187960,0.184561,0.206687,0.100105,0.672564,0.342395,0.245141,0.543438,9.925845
45,6,0.000000,0.063831,0.246174,0.081467,0.843877,0.729129,0.212637,0.549469,9.873352
46,7,0.144329,0.023762,0.264372,0.318432,0.733935,0.477305,0.011577,0.509664,9.823077
47,8,0.000000,0.297731,0.172213,0.083311,0.586389,0.569622,0.144597,0.590291,9.914572
48,9,0.000000,0.017910,0.132118,0.154352,0.655318,0.472239,0.256313,0.583388,9.944913
49,10,0.082999,0.200634,0.157860,0.204604,0.760760,0.526395,0.248841,0.474721,NaN

Reading a dataframe,

In [3]:
# Importing
import pandas as pd

# Reading evalutions,
df = pd.read_csv("dataset/func_1_evals.csv")
df

    Query Number        x1        x2           f(X)
0             -1  0.319404  0.762959   1.322677e-79
1             -2  0.574329  0.879898   1.033078e-46
2             -3  0.731024  0.733000   7.710875e-16
3             -4  0.840353  0.264732  3.341771e-124
4             -5  0.650114  0.681526  -3.606063e-03
5             -6  0.410437  0.147554  -2.159249e-54
6             -7  0.312691  0.078723  -2.089093e-91
7             -8  0.683418  0.861057   2.535001e-40
8             -9  0.082507  0.403488   3.606771e-81
9            -10  0.883890  0.582254   6.229856e-48
10             1  0.732787  0.733181   3.589724e-16
11             2  0.500000  0.450000  -5.847155e-06
12             3  0.716104  0.731080   2.491766e-13
13             4  0.701749  0.728584   2.669673e-11
14             5  0.697745  0.727874   8.202194e-11
15             6  0.691083  0.726420   4.836324e-10
16             7  0.682311  0.724407   3.393199e-09
17             8  0.678779  0.723449   6.231793e-09
18             9  0.668638  0.720203   6.349179e-09
19            10  0.678031  0.738179   2.249596e-11
20            11  0.671027  0.721208            NaN
21            12       NaN       NaN            NaN